### ISSUE TITLE
Sometimes {{query-block}} does not show up the query build interface. I have to refresh the page, and it will show up.

### ISSUE THREAD

**Issue by chengxu999** [dvargas92495/roamjs-query-builder#1]

**Comment by dvargas92495** [comment]
Do you have steps that lead to when it doesn't show up or a video showing this behavior?

**Comment by chengxu999** [comment]
> Do you have steps that lead to when it doesn't show up or a video showing this behavior?

https://user-images.githubusercontent.com/102467835/162907825-9ea78bd4-a377-4cf6-ae58-d0da70930c7c.mp4

![image](https://user-images.githubusercontent.com/102467835/162907635-535ed2e9-7d06-4886-881a-c83d6c3e7b33.png)

**Comment by dvargas92495** [comment]
Are there any errors thrown in the console?

**Comment by chengxu999** [comment]
I typed {{query-block}} and then return. The settings are all default.



发自我的iPhone


------------------ Original ------------------
From: David Vargas ***@***.***&gt;
Date: Mon,Apr 11,2022 9:24 PM
To: dvargas92495/roamjs-query-builder ***@***.***&gt;
Cc: chengxu999 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [dvargas92495/roamjs-query-builder] Sometimes {{query-block}} does not show up the query build interface. I have to refresh the page, and it will show up. (Issue #1)






Do you have steps that lead to when it doesn't show up or a video showing this behavior?

**Comment by chengxu999** [comment]
No, I did not see any errors…


If I go to child blocks of {{query-block}}, and type in direct query conditions, the query box will show up again.



发自我的iPhone


------------------ Original ------------------
From: David Vargas ***@***.***&gt;
Date: Wed,Apr 13,2022 11:05 AM
To: dvargas92495/roamjs-query-builder ***@***.***&gt;
Cc: chengxu999 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [dvargas92495/roamjs-query-builder] Sometimes {{query-block}} does not show up the query build interface. I have to refresh the page, and it will show up. (Issue #1)






Are there any errors thrown in the console?

**Comment by dvargas92495** [comment]
hm I still see it working on my end. What browser are you using?

**Comment by chengxu999** [comment]
I use Chrome. I guess it might be a conflict with some extension I installed? I am not sure.&nbsp;





------------------ Original ------------------
From: David Vargas ***@***.***&gt;
Date: Wed,Apr 13,2022 11:21 PM
To: dvargas92495/roamjs-query-builder ***@***.***&gt;
Cc: chengxu999 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [dvargas92495/roamjs-query-builder] Sometimes {{query-block}} does not show up the query build interface. I have to refresh the page, and it will show up. (Issue #1)






hm I still see it working on my end. What browser are you using?

**Comment by dvargas92495** [comment]
are you still seeing issues?

**Comment by chengxu999** [comment]
I think this is fixed! Much thanks!



发自我的iPhone


------------------ Original ------------------
From: David Vargas ***@***.***&gt;
Date: Thu,Jun 30,2022 7:43 AM
To: dvargas92495/roamjs-query-builder ***@***.***&gt;
Cc: chengxu999 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [dvargas92495/roamjs-query-builder] Sometimes {{query-block}} does not show up the query build interface. I have to refresh the page, and it will show up. (Issue #1)





 
are you still seeing issues?
