### ISSUE TITLE
Can I use query builder to collect all links within two pages?

### ISSUE THREAD

**Issue by Orisik** [dvargas92495/roamjs-query-builder#11]
We can use the page filter to know all the links on a page, but How can I collect all the links on **two pages**.

![image](https://user-images.githubusercontent.com/83809518/197324348-7aa5475d-763b-4779-a8bf-280cf037e42f.png)

This problem has been bothering me for a long time. Thank you so much

**Comment by dvargas92495** [comment]
Yea should be doable

Could you show what you have so far and I could let you know what's missing?

**Comment by dvargas92495** [comment]
For any future support - ask in the #roam_js channel on Slack
