### ISSUE TITLE
Sortable Linked References icon disappears

### ISSUE THREAD

**Issue by ViTuDia** [dvargas92495/roamjs-query-builder#22]
Sortable Linked References icon only appears when having the button switched off and on again. (It happens that the icon disappears after reloading Roam while this option having switched on in settings)

<img width="663" alt="Screenshot 2023-01-08 at 15 23 19" src="https://user-images.githubusercontent.com/59163092/211201484-a501ad4c-0b97-40ce-b0cd-8be8f8a00a7a.png">

**Comment by dvargas92495** [comment]
Am able to reproduce, investigating
