### ISSUE TITLE
Support adding aliases to Query Blocks

### ISSUE THREAD

**Issue by dvargas92495** [dvargas92495/roamjs-query-builder#30]
Then the QUERYBUILDER smartblock command should be able to reference these aliases from the block or from the page name

**Comment by dvargas92495** [comment]
![Image](https://user-images.githubusercontent.com/7143571/217053606-33bce062-e7e5-44bf-bc8c-4d92be8468c4.png)

**Comment by mdroidian** [comment]
Do you mean something like


![Image](https://user-images.githubusercontent.com/3792666/219186620-baa336ad-d5d7-4975-8c15-3b8ef93ff231.png)
