### ISSUE TITLE
Alias on Query Drawer / Query Pages

### ISSUE THREAD

**Issue by mdroidian** [dvargas92495/roamjs-query-builder#47]
While making the docs for #44, I noticed that missed looking at `Query Drawer` / `Query Pages`

`Query Drawer` doesn't serve a purpose
![image](https://user-images.githubusercontent.com/3792666/219898767-817e3429-db01-46c6-bd92-74ec57666351.png)

I thought the same would be true for `Query Pages` ... but ...
![image](https://user-images.githubusercontent.com/3792666/219898754-d0bab9ff-322f-4d46-abbf-76307f4df846.png)

Where is `{{query block:whyDoesThisWork}}` stored for `Query Pages`?

# Possible solution
adding this check to QueryEditor.tsx to remove it from the `Query Drawer`

`const isQueryDrawer = getPageTitleByPageUid(parentUid) === "roam/js/query-builder/drawer";`

**Comment by dvargas92495** [comment]
I think I would prefer passing in a prop that is `true` for Query Blocks but by default false
