### ISSUE TITLE
Find 'node' where

### ISSUE THREAD

**Issue by mujihuz** [dvargas92495/roamjs-query-builder#5]
I've been facing two issues: 
1) The default query that appears in pages and within blocks shows 'Find nodes where'
2) My list of selections are very few compared to the one shown in the video.

My query builder used to work fine and show all the items in the list. But it has become like this for a few days now and no matter how many times I delete and reinstall the extension (either manually or via the roam depot which was added recently) it does not fix the 2 issues mentioned above. 
I'm not sure if its something I've done to my roam graph or something with the extension itself, so I thought i'd ask here. 
Thanks anyway for the great extension.

**Comment by dvargas92495** [comment]
The default query was intentionally changed to `find node where`. This was to remove confusion since the query builder could return blocks _or_ pages.

Do you have a video showing the issue with the few condition options?

**Comment by mujihuz** [comment]
Thanks. Is there a way to change it to find block or page?

https://user-images.githubusercontent.com/86186715/180628399-17f607a4-d502-4bc3-8453-fc7bb486de94.mov

I have added a video relevant to the issue.

**Comment by dvargas92495** [comment]
To be clear - it still searches block or page, it's just being labelled as "node". are you asking to see if that label could say block or page?

The drop down is an auto complete, so once you start typing it will show the rest of the supported options - it cuts off at 10 when there's more than 10

**Comment by mujihuz** [comment]
Thanks David. You were right. Really appreciate your help.
