### ISSUE TITLE
node is only target option

### ISSUE THREAD

**Issue by garcle** [dvargas92495/roamjs-query-builder#6]
Installed this via RoamDepot  (previously it was installed via Roam marketplace)
![query builder issue](https://user-images.githubusercontent.com/6287784/181721784-b848d067-e006-4014-af57-98961d6db5a0.png)

I only get an option for Node as a target

**Comment by dvargas92495** [comment]
This is expected behavior - as you add more conditions, more placeholders become available

**Comment by garcle** [comment]
![query-builder help example](https://user-images.githubusercontent.com/6287784/181871879-20038f20-39fe-4d0b-a401-e80bdd8ccb66.png)
How do I get the values shown in the query builder help example??
What woudl the first "find" be to get from 'node' to 'block'?

**Comment by dvargas92495** [comment]
`'node'` and `'block'` are just labels - they're interchangeable. We renamed the initial label from `'block'` to `'node'` to communicate that the query could return pages _or_ blocks, not just blocks

you should be able to recreate this example, but with `'node'` instead of `'block'`

**Comment by garcle** [comment]
> `'node'` and `'block'` are just labels - they're interchangeable. We renamed the initial label from `'block'` to `'node'` to communicate that the query could return pages _or_ blocks, not just blocks
> 
> you should be able to recreate this example, but with `'node'` instead of `'block'`

Thank you, I understand now,. and the example worked. :)
