### ISSUE TITLE
Allow user to set custom width for selection columns in Results View

### ISSUE THREAD

**Issue by mdroidian** [dvargas92495/roamjs-query-builder#69]
From Michael Shulman: https://roamresearch.slack.com/archives/C04H4739402/p1682454297896769

> Would it be possible to allow resizing Query columns? There’s a lot of lost space without that affordance.

![image](https://user-images.githubusercontent.com/3792666/234405807-e429f4e3-c231-49f3-9364-8aee5ec0dbb4.png)

**Comment by dvargas92495** [comment]
I thought I had this written down already - definitely need this
