### ISSUE TITLE
nothing is selected?

### ISSUE THREAD

**Issue by vzaidman** [dvargas92495/roamjs-query-builder#7]
Hey! Any idea why nothing is selected as the "Page"? Should `node:page` work?
![image](https://user-images.githubusercontent.com/5188459/185755295-833d78d7-578f-4ab6-b7c8-ea9e00241619.png)

**Comment by dvargas92495** [comment]
Yes, it's because you don't have an intermediary node called `page`.

Instead of `node:page`, try setting it to `node:QQ-DATE`

**Comment by vzaidman** [comment]
It works!
Why can't I set only "QQ-DATE" ?

**Comment by dvargas92495** [comment]
That was the only one you defined. `node:PARENT` would return you the block represented by `PARENT`
