### ISSUE TITLE
Feature Request: Remember Column View Setting

### ISSUE THREAD

**Issue by digitalmaster** [dvargas92495/roamjs-query-builder#8]
Today, when I select column view it's only temporary. If I rerun the query or leave the page and come back it resets. Would be great if this were stored. 

<img width="440" alt="CleanShot 2022-10-08 at 22 26 24@2x" src="https://user-images.githubusercontent.com/1279335/194734693-6fdb7fd4-9f54-49a3-82c4-07da01d83919.png">

**Comment by dvargas92495** [comment]
This would be a bug - I would expect this to be supported already. Will investigate

**Comment by digitalmaster** [comment]
Just realized that I could edit the config data directly. That fixed it for me. Just fyi :)

**Comment by dvargas92495** [comment]
Yes that is a workaround, but that config data not responding to UI changes is still a bug we plan to fix
