### ISSUE TITLE
Question: How do I add an "or" condition?

### ISSUE THREAD

**Issue by digitalmaster** [dvargas92495/roamjs-query-builder#9]
I have a case where I want to add a condition where the page referenced could be either #p1 or #p2 or p3. If I add these as separate conditions it looks like it adds em as an "and" operation.

How would you go about achieving this? I'm sure i'm doing something wrong here 🙈 
![image](https://user-images.githubusercontent.com/1279335/196442674-b1693a07-8dbe-45a4-9d43-88e9dbd3626c.png)

**Comment by dvargas92495** [comment]
Still in development: https://github.com/dvargas92495/roamjs-query-builder/pull/4

but often times there are more performant ways to workaround the OR. In this case, each of `p1`, `p2`, and `p3` could themselves have a tag on them, let's say `#Priority`, which would allow you to replace

```
node        references  title   p3, p2, p1
```

with

```
node        references        tag
tag         has child         block
block       references title  Priority      
```

**Comment by digitalmaster** [comment]
> Still in development: https://github.com/dvargas92495/roamjs-query-builder/pull/4

Nice 👏🏽

> Re: Workaround

Hmm.. not sure I follow. Ultimately what I'd like to be able to do is just get a sorted list of all the TODO's on that page with a priority tag (p1, p2, p3).

**Comment by dvargas92495** [comment]
Right all I'm saying is you can concretely define what it means for a tag to be a priority tag. In this way, you are more concretely querying for what you intended:
![Screen Shot 2022-10-19 at 10 13 58 AM](https://user-images.githubusercontent.com/7143571/196716363-9d715609-6eb8-4dbc-adaf-8954c5ca7d1e.png)

**Comment by digitalmaster** [comment]
Oh brilliant. That works 🥳 .. Thank you
